spring.application.name=auth-server

server.port=9000

auth-server.issuer-uri=${AUTH_SERVER_ISSUER_URI:http://localhost:9000}

auth-server.market-app-client.id=${MARKET_APP_CLIENT_ID:market-app-client}
auth-server.market-app-client.secret=${MARKET_APP_CLIENT_SECRET:market-app-secret}
