spring.application.name=my-market-app

server.port=8080

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/market_db
spring.r2dbc.username=gpay
spring.r2dbc.password=${DB_PASSWORD:gpay}

spring.r2dbc.pool.initial-size=2
spring.r2dbc.pool.max-size=10
spring.r2dbc.pool.max-idle-time=30s
spring.r2dbc.pool.validation-depth=local

