spring.application.name=my-market-app

server.port=8080

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

spring.datasource.url=jdbc:postgresql://localhost:5432/market_db
spring.datasource.username=gpay
spring.datasource.password=${DB_PASSWORD:gpay}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO
