spring.application.name=payment-service

server.port=8081

payment.balance.initial=${PAYMENT_INITIAL_BALANCE:100000}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_SERVER_ISSUER_URI:http://localhost:9000}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_SERVER_ISSUER_URI:http://localhost:9000}/oauth2/jwks
